export const GET_PACKAGES = "GET_PACKAGES"
export const ADD_PACKAGE = "ADD_PACKAGE"
export const UPDATE_PACKAGE = "UPDATE_PACKAGE"
export const DELETE_PACKAGE = "DELETE_PACKAGE"

export const SET_SELECTED_PACKAGE = "SET_SELECTED_PACKAGE"

